"""Initial clean migration

Revision ID: bb5c2ac77950
Revises: 
Create Date: 2025-09-01 09:50:59.969334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5c2ac77950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_codeset',
    sa.Column('codeset_id', sa.String(length=36), nullable=False),
    sa.Column('codeset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('codeset_id'),
    sa.UniqueConstraint('codeset_code')
    )
    op.create_table('custom_meta_group',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('group_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_code')
    )
    op.create_table('tx_taxonomy',
    sa.Column('taxonomy_id', sa.String(length=36), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('taxonomy_id'),
    sa.UniqueConstraint('taxonomy_code')
    )
    op.create_table('cm_code',
    sa.Column('code_id', sa.String(length=36), nullable=False),
    sa.Column('codeset_id', sa.String(length=36), nullable=False),
    sa.Column('code_key', sa.String(length=150), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['codeset_id'], ['cm_codeset.codeset_id'], ),
    sa.PrimaryKeyConstraint('code_id'),
    sa.UniqueConstraint('codeset_id', 'code_key', name='uq_code_key_per_set')
    )
    op.create_table('custom_meta_item',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('type_kind', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_json', sa.Text(), nullable=True),
    sa.Column('selection_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['custom_meta_group.group_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('tx_term',
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('taxonomy_id', sa.String(length=36), nullable=False),
    sa.Column('term_key', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('parent_term_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_term_id'], ['tx_term.term_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['tx_taxonomy.taxonomy_id'], ),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('taxonomy_id', 'term_key', name='uq_term_key_per_taxonomy')
    )
    op.create_index(op.f('ix_tx_term_parent_term_id'), 'tx_term', ['parent_term_id'], unique=False)
    op.create_index(op.f('ix_tx_term_taxonomy_id'), 'tx_term', ['taxonomy_id'], unique=False)
    op.create_table('cm_code_version',
    sa.Column('code_version_id', sa.String(length=36), nullable=False),
    sa.Column('code_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('label_default', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('parent_code_id', sa.String(length=36), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['cm_code.code_id'], ),
    sa.ForeignKeyConstraint(['parent_code_id'], ['cm_code.code_id'], ),
    sa.PrimaryKeyConstraint('code_version_id'),
    sa.UniqueConstraint('code_id', 'version_no', name='uq_code_version_no')
    )
    op.create_index(op.f('ix_cm_code_version_code_id'), 'cm_code_version', ['code_id'], unique=False)
    op.create_table('custom_meta_value',
    sa.Column('value_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['custom_meta_item.item_id'], ),
    sa.PrimaryKeyConstraint('value_id'),
    sa.UniqueConstraint('target_type', 'target_id', 'item_id', name='uq_value_target_item')
    )
    op.create_index('ix_value_target', 'custom_meta_value', ['target_type', 'target_id'], unique=False)
    op.create_table('tx_term_content',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['tx_term.term_id'], ),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('term_id')
    )
    op.create_table('custom_meta_value_version',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('value_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('code_id', sa.String(length=36), nullable=True),
    sa.Column('taxonomy_term_id', sa.String(length=36), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['cm_code.code_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_term_id'], ['tx_term.term_id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['custom_meta_value.value_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('value_id', 'version_no', name='uq_value_version_no')
    )
    op.create_index(op.f('ix_custom_meta_value_version_value_id'), 'custom_meta_value_version', ['value_id'], unique=False)
    op.create_table('tx_term_content_version',
    sa.Column('content_version_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('tx_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['tx_term_content.content_id'], ),
    sa.PrimaryKeyConstraint('content_version_id'),
    sa.UniqueConstraint('content_id', 'version_no', name='uq_term_content_version_no')
    )
    op.create_index(op.f('ix_tx_term_content_version_content_id'), 'tx_term_content_version', ['content_id'], unique=False)
    op.create_table('custom_meta_value_version_term',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['tx_term.term_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['custom_meta_value_version.version_id'], ),
    sa.PrimaryKeyConstraint('version_id', 'term_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_meta_value_version_term')
    op.drop_index(op.f('ix_tx_term_content_version_content_id'), table_name='tx_term_content_version')
    op.drop_table('tx_term_content_version')
    op.drop_index(op.f('ix_custom_meta_value_version_value_id'), table_name='custom_meta_value_version')
    op.drop_table('custom_meta_value_version')
    op.drop_table('tx_term_content')
    op.drop_index('ix_value_target', table_name='custom_meta_value')
    op.drop_table('custom_meta_value')
    op.drop_index(op.f('ix_cm_code_version_code_id'), table_name='cm_code_version')
    op.drop_table('cm_code_version')
    op.drop_index(op.f('ix_tx_term_taxonomy_id'), table_name='tx_term')
    op.drop_index(op.f('ix_tx_term_parent_term_id'), table_name='tx_term')
    op.drop_table('tx_term')
    op.drop_table('custom_meta_item')
    op.drop_table('cm_code')
    op.drop_table('tx_taxonomy')
    op.drop_table('custom_meta_group')
    op.drop_table('cm_codeset')
    # ### end Alembic commands ###
